obstacle_range: 6.0         ##
raytrace_range: 6.0         ##
footprint: [[0.3, 0.15], [0.3, -0.15], [-0.35, -0.15], [-0.35, 0.15]]
robot_radius: 0.01
inflation_radius: 0.5
max_obstacle_height: 1.0
min_obstacle_height: 0.0
# observation_sources: scan
# scan: {data_type: LaserScan, topic: /merged_laserscan, marking: true, clearing: true, expected_update_rate: 3.3}
observation_sources: Scan
Scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 3.3}